export const initData = {
    fecha: "",
    total: 0,
    sexo: {
      pregunta: "",
      totalDeDatos: 0,
      fAbsoluta: [],
      labels: [],
      fPorcentual: [],
    },
    "edad_14-25": {
      pregunta: "",
      totalDeDatos: 0,
      fAbsoluta: [],
      labels: [],
      fPorcentual: [],
    },
    "edad_26-40": {
      pregunta: "",
      totalDeDatos: 0,
      fAbsoluta: [],
      labels: [],
      fPorcentual: [],
    },
    "edad_41-55": {
      pregunta: "",
      totalDeDatos: 0,
      fAbsoluta: [],
      labels: [],
      fPorcentual: [],
    },
    "edad_56-99": {
      pregunta: "",
      totalDeDatos: 0,
      fAbsoluta: [],
      labels: [],
      fPorcentual: [],
    },
    p1: {
      pregunta: "",
      totalDeDatos: 0,
      fAbsoluta: [],
      labels: [],
      fPorcentual: [],
    },
    p2: {
      pregunta: "",
      totalDeDatos: 0,
      fAbsoluta: [],
      labels: [],
      fPorcentual: [],
    },
    p3: {
      pregunta: "",
      totalDeDatos: 0,
      fAbsoluta: [],
      labels: [],
      fPorcentual: [],
    },
    p4: {
      pregunta: "",
      totalDeDatos: 0,
      fAbsoluta: [],
      labels: [],
      fPorcentual: [],
    },
    p5: {
      pregunta: "",
      totalDeDatos: 0,
      fAbsoluta: [],
      labels: [],
      fPorcentual: [],
    },
    p6: {
      pregunta: "",
      totalDeDatos: 0,
      fAbsoluta: [],
      labels: [],
      fPorcentual: [],
    },
    p7: {
      pregunta: "",
      totalDeDatos: 0,
      fAbsoluta: [],
      labels: [],
      fPorcentual: [],
    },
    p8: {
      pregunta: "",
      totalDeDatos: 0,
      fAbsoluta: [],
      labels: [],
      fPorcentual: [],
    },
    p9: {
      pregunta: "",
      totalDeDatos: 0,
      fAbsoluta: [],
      labels: [],
      fPorcentual: [],
    },
    p10: {
      pregunta: "",
      totalDeDatos: 0,
      fAbsoluta: [],
      labels: [],
      fPorcentual: [],
    },
    p11_1: {
      pregunta: "",
      totalDeDatos: 0,
      fAbsoluta: [],
      labels: [],
      fPorcentual: [],
    },
    p11_2: {
      pregunta: "",
      totalDeDatos: 0,
      fAbsoluta: [],
      labels: [],
      fPorcentual: [],
    },
    p12: {
      pregunta: "",
      totalDeDatos: 0,
      fAbsoluta: [],
      labels: [],
      fPorcentual: [],
    },
    p13: {
      pregunta: "",
      totalDeDatos: 0,
      fAbsoluta: [],
      labels: [],
      fPorcentual: [],
    },
    p14: {
      pregunta: "",
      totalDeDatos: 0,
      fAbsoluta: [],
      labels: [],
      fPorcentual: [],
    },
    p15: {
      pregunta: "",
      totalDeDatos: 0,
      fAbsoluta: [],
      labels: [],
      fPorcentual: [],
    },
    p16: {
      pregunta: "",
      totalDeDatos: 0,
      fAbsoluta: [],
      labels: [],
      fPorcentual: [],
    },
  }
  
  